model:
  name: 'https://tfhub.dev/google/nonsemantic-speech-benchmark/trillsson5/1'
  bilstm: false
  h: 128
  w: 128

data:
  develop: false
  batch_size: 8
  root_dir: '/netscratch/herzig/datasets/BabyCry3'
  n_fold: 8
  shuffle: true

mode: 'train'

train_config:
  epochs: 30